title: BRBC Family Camp
baseURL: /
params:
  layout_type: full-width
  style: classic
  palette: blue
  mode: light
  base_font: sans-serif
  header:
    title: BRBC Family Camp
    logo: images/cool-steel.jpeg
    logo_alt: BRBC Family Camp
    has_primary_nav: false
    has_secondary_nav: true
    secondary_nav_links:
      - label: About
        url: /about
        style: link
      - label: Register
        url: >-
          https://docs.google.com/forms/d/e/1FAIpQLSeV4jZoqhO2ilDvUX1CgXss0UcEXxC09oAdlxf9ieQF4O26tA/viewform
        style: primary
      - label: Accommodations
        url: /accommodations
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
      - label: lorem-ipsum
        url: '#'
        style: link
        has_icon: false
        icon: arrow-left
        icon_position: right
        new_window: false
        no_follow: false
        type: action
    has_anncmnt: false
  footer:
    has_primary_nav: false
    has_secondary_nav: false
    has_tertiary_nav: false
    has_social: false
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=event&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>
  domain: 'https://oceanic-tulip-ef834.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
